### PR TITLE
add postgres collector

### PR DESCRIPTION
**Pull request by ilyam8**
Part of netdata/netdata#13387

This PR adds the initial version of Postgres collector. The initial version implements:

- collecting databases statistics (metrics from [pg_stat_database](https://www.postgresql.org/docs/9.2/monitoring-stats.html#PG-STAT-DATABASE-VIEW)).

| Metric              |         Dimensions         |     Units      |
|---------------------|:--------------------------:|:--------------:|
| db_transactions     |    committed, rollback     | transactions/s |
| db_connections      |        connections         |  connections   |
| db_buffer_cache     |         hit, miss          |    blocks/s    |
| db_read_operations  |     returned, fetched      |     rows/s     |
| db_write_operations | inserted, deleted, updated |     rows/s     |
| db_conflicts        |         conflicts          |   queries/s    |
| db_deadlocks        |         deadlocks          |   deadlocks/s  |
| db_temp_files       |          written           |    files/s     |
| db_temp_files_data  |          written           |      B/s       |
| db_size             |            size            |       B        |

- labels: only one - `database`.

### CODE REVIEW

**Comment by ilyam8** [comment]
@thiagoftsm that is wip, please don't spam with comments.

**Comment by thiagoftsm** [comment]
> And please consider commenting on PR, not commits.

All right, I will follow this. :handshake:

**Comment by ilyam8** [comment]
@thiagoftsm the Postgres collector still wip, I just added databases statistics. The readme doesn't is not finished, I will be updating it in the upcoming PRs.

**Comment by thiagoftsm** [comment]
> @thiagoftsm the Postgres collector still wip, I just added databases statistics. The readme doesn't is not finished, I will be updating it in the upcoming PRs.

I almost ping you saying that we are having wrong documentation citing `mariadb` and common `mysql` queries, but I open the PR and I saw this message :smile: .

**Pull request merged**
