### PR TITLE
add proxysql service monitoring plugin

### PR DESCRIPTION
**Pull request by yasharne**
Fixes: netdata/netdata#13316

---

This plugin works for now, but it is not gathering all metrics from ProxySQL. So I will create it as a draft.
I just want an initial preview from the maintainers.
Here is a screenshot from the working plugin:
image

I have a question, if you take a look at the screenshot, there is a text:
```
questions total number of queries sent from frontends, slow_queries number of queries that ran for longer than the threshold in milliseconds defined in global variable mysql-long_query_time.
```

I didn't add this section and I don't know where is it coming from, but how can I add my own explanation to some charts?

### CODE REVIEW

**Comment by ilyam8** [comment]
> I didn't add this section and I don't know where is it coming from, but how can I add my own explanation to some charts?

The info you are referring to is coming from the [dashboard_info.js](dashboard_info.js) file.

See for instance https://github.com/netdata/netdata/pull/13181 PR.

There are 3 maps:

- netdataDashboard.menu (info for top-level section (use the collector name), we use it to add an icon, a short description)
- netdataDashboard.submenu (info for subsections, attached based on charts family)
- netdataDashboard.context (info for charts, attached based on charts context)

**Comment by yasharne** [comment]
Thanks for reviewing @ilyam8 , one more thing, some metrics (rows in the tables) are currently in the ToDo state in the ProxySQL project, the key exists but the value is always zero.
Should I keep those metrics? or comment them out? or remove them?

**Comment by ilyam8** [comment]
Hey, @yasharne. Do you need any help?

**Comment by yasharne** [comment]
Hi @ilyam8 I was busy with some internal tasks, I will resume this PR shortly after

**Comment by ilyam8** [comment]
Hey, @yasharne. Can you give me a short guide (docker preferable) on how to set up a ProxySQL instance so I can check the collector? Also, we need a readme file.

**Comment by yasharne** [comment]
> Hey, @yasharne. Can you give me a short guide (docker preferable) on how to set up a ProxySQL instance so I can check the collector? Also, we need a readme file.

Hi @ilyam8 I used this repository to test the collector: https://github.com/rongfengliang/proxysql-docker-compose
you just have to add `network_mode: "host"` to the end of the `docker-compose` to be able to connect using `stats:stats` username/password

**Comment by ilyam8** [comment]
Thanks, looks good overall. I am going to merge, do some tests and apply any changes (if needed) in a following PR.

**Pull request merged**
