### PR TITLE
sync orchestrator

### PR DESCRIPTION
**Pull request by Wing924**

### CODE REVIEW

**Comment by ilyam8** [comment]
i see more changed then in description.

How did you update it?

i did

> go get github.com/netdata/go-orchestrator@v0.0.0-20190312061432-547df3f9ece6

```dif
[lgz :go.d.plugin](master *%)git diff go.sum go.mod
diff --git a/go.mod b/go.mod
index fc0848f..9f60e7e 100644
--- a/go.mod
+++ b/go.mod
@@ -6,7 +6,7 @@ require (
        github.com/go-sql-driver/mysql v1.4.1
        github.com/hpcloud/tail v1.0.0
        github.com/miekg/dns v1.1.4
-       github.com/netdata/go-orchestrator v0.0.0-20190220185207-68fba67151c9
+       github.com/netdata/go-orchestrator v0.0.0-20190312061432-547df3f9ece6
        github.com/prometheus/common v0.2.0 // indirect
        github.com/prometheus/prometheus v2.5.0+incompatible
        github.com/stretchr/testify v1.3.0
diff --git a/go.sum b/go.sum
index 9680488..5d8fa5b 100644
--- a/go.sum
+++ b/go.sum
@@ -36,6 +36,8 @@ github.com/mitchellh/go-homedir v1.1.0/go.mod h1:SfyaCUpYCn1Vlf4IUYiD9fPX4A5wJrk
 github.com/mwitkow/go-conntrack v0.0.0-20161129095857-cc309e4a2223/go.mod h1:qRWi+5nqEBWmkhHvq77mSJWrCKwh8bxhgT7d/eI7P4U=
 github.com/netdata/go-orchestrator v0.0.0-20190220185207-68fba67151c9 h1:kD3/zOl8M1tFIlNd9T/ty6Zq2AVXXd4DAhG8u/wxHn4=
 github.com/netdata/go-orchestrator v0.0.0-20190220185207-68fba67151c9/go.mod h1:GkRx+XaReZcgCkm8nlSM+90ctTww5l0G9Qtxx8ZkvYY=
+github.com/netdata/go-orchestrator v0.0.0-20190312061432-547df3f9ece6 h1:fS3/R+LVSdfIK5R+0aI0lsCMszGBsElfq7IZqnuWzWk=
+github.com/netdata/go-orchestrator v0.0.0-20190312061432-547df3f9ece6/go.mod h1:GkRx+XaReZcgCkm8nlSM+90ctTww5l0G9Qtxx8ZkvYY=
 github.com/pkg/errors v0.8.0/go.mod h1:bwawxfHBFNV+L2hUp1rHADufV3IMtnDRdf1r5NINEl0=
 github.com/pmezard/go-difflib v1.0.0 h1:4DBwDE0NGyQoBHbLQYPwSUPoCMWR5BEzIk/f1lZbAQM=
 github.com/pmezard/go-difflib v1.0.0/go.mod h1:iKH77koFhYxTK1pcRnkKkqfTogsbg7gZNVY4sRDYZ/4=
```

**Comment by Wing924** [comment]
```
go get -u github.com/netdata/go-orchestrator
```

**Comment by ilyam8** [comment]
it seems that this command updated more stuff that it should

**Comment by Wing924** [comment]
oh.. `-u` is bad.

**Pull request merged**
