### PR TITLE
modules/mysql: collect user statistics `Cpu_time`

### PR DESCRIPTION
**Pull request by ilyam8**
Fixes: #442

> The cumulative CPU time elapsed while servicing this user's connections.

```
Cpu_time: 0.0021376
```

Python [`userstas_cpu` chart](https://github.com/netdata/netdata/blob/83c0121c53c25c58e4308e9723f5395af29ef9c0/collectors/python.d.plugin/mysql/mysql.chart.py#L667-L671) units is `percentage`.

I dont get how we calc percentage 🤔 

https://github.com/netdata/netdata/blob/83c0121c53c25c58e4308e9723f5395af29ef9c0/collectors/python.d.plugin/mysql/mysql.chart.py#L961-L962

---

ok i got it - we need `mul` 100, `div` update_every and `algorithm` incremental.

### CODE REVIEW

**Comment by ilyam8** [comment]
@kam1kaze could you help here? i think python `userstats_cpu` chart is wrong

**Review by vlvkobal — APPROVED** [review]

**Review by thiagoftsm — APPROVED** [review]
LGTM!

**Comment by kam1kaze** [comment]
@ilyam8 as you wrote we need to multiply by 100. Does python script not have it? I thought that 4th param is multiplicator.

**Comment by ilyam8** [comment]
> Does python script not have it?

Yeah, it does it, you are right.

I see python:
- doesnt take into account that `Cpu_time` is `float` and we need to multiply it by some precision and add this precision as divisor (netdata's external plugins api allows only `int` values).
- doesnt take into accout `update_every` so it works ~correctly only when `update_every` is 1.

**Pull request merged**
