### PR TITLE
vsphere: improve exported metrics and cleanup

### PR DESCRIPTION
**Pull request by ilyam8**
Fixes: #336

### CODE REVIEW

**Comment by ilyam8** [comment]
@nghtrifork

Could you test the PR? i have no vsphere lab atm.

As discussed new options are

```yaml
  - name     : vcenter1
     url      : https://203.0.113.0
     username : admin@vsphere.local
     password : somepassword
     vm_metrics:
       - name: yes
       - host: yes
       - cluster: yes
       - datacenter: yes
     host_metrics:
       - name: yes
       - cluster: yes
       - datacenter: yes
```

VM template with all enabled options: 

> `vm-ID_name-NAME_host-HOSTNAME_cluster-CLUSTERNAME_datacetner-DATACENTERNAME`

Examples:

```console
host-20_name-DC0_H0_cluster-DC0_H0_datacenter-DC0_cpu_usage_total

vm-62_name-DC0_C0_RP0_VM1_host-DC0_C0_H0_cluster-DC0_C0_datacenter-DC0_system_uptime
```

**Comment by ilyam8** [comment]
- `git clone https://github.com/ilyam8/go.d.plugin --branch=vshere_improve_exported_metrics`
- `cd go.d.plugin`
- `make`
- stop netdata.service
- `sudo cp bin/godplugin /opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin # change path if needed`
- change config, add new options
- start netdata service

**Comment by nghtrifork** [comment]
Hi @ilyam8 
You are amazingly fast
I will try to test it in the upcoming week and let you know of the result.

**Comment by ilyam8** [comment]
Ok, i am going to merge, it pass test. If there are some problems i will fix them right after your tests @nghtrifork

**Comment by ilyam8** [comment]
@scomoletti probaly you are interested in this feature too

It adds hierarchy info to the chart id.

Example `allmetrics?format=json` data for vm with

```yaml
  - name     : vcenter1
     url      : https://203.0.113.0
     username : admin@vsphere.local
     password : somepassword
     vm_metrics:
       name: yes
       host: yes
       cluster: yes
       datacenter: yes
```

```json
	"vsphere_vc01.mydomain.com.vm-718_name-NAME_host-HOSTNAME_cluster-CLUSTERNAME_datacenter-DATACENERNAME_cpu_usage_total": {
		"name":"vsphere_vc01.mydomain.com.vm-718_name-NAME_host-HOSTNAME_cluster-CLUSTERNAME_datacenter-DATACENERNAME_cpu_usage_total",
		"context":"vsphere.cpu_usage_total",
		"units":"percentage",
		"last_updated": 1569550720,
		"dimensions": {
			"vm-718_cpu.usage.average": {
				"name": "used",
				"value": 7.7200000
			}
		}
	},
```

**Comment by nghtrifork** [comment]
@ilyam8 is go.d plugin verison locked in netdata? After I get to test it and verify it will it go live in the next netdata version?

**Comment by ilyam8** [comment]
There is hardcoded current version in the netdata repo
https://github.com/netdata/netdata/blob/master/packaging/go.d.version

Netdata installer/updater download curret version only if:
 - there is no `go.d.plugin`
 - current version > actual

So if you compile it yourself it wont be updated by netdata updater until 0.17.0 is out.

But you need to compile it using `make` or `./hack/go-build.sh` script. (it adds version).

This will do
https://github.com/netdata/go.d.plugin/pull/352#issuecomment-592986100

**Comment by nghtrifork** [comment]
I have followed your instructions regarding building and replacing/extracting the newer version, but perhaps I am doing something wrong

I am running netdata in docker container so I build and copied the godplugin to /usr/libexec/netdata/plugins.d/ but when it fails when it's starting. I don't have a vsphere instance here with me, but I wanted to test I can actually build and run it prior to testing on dev env

Building:

 ```
~/projects/go.d.plugin   master  git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
 ~/projects/go.d.plugin   master  make
go mod download
go vet ./...
go test ./... -race -cover -covermode=atomic
<test results>
rm -rf bin
hack/go-build.sh
Building binaries for version: v0.16.0-2-g5015bcf
Building for os/arch darwin/amd64
 ~/projects/go.d.plugin   master  ls -l bin/
total 50952
-rwxr-xr-x  1 ngh  staff  26085120 Mar  1 18:59 godplugin
 ~/projects/go.d.plugin   master 

```

then I copy it to netdata container:

`cp /files/godplugin /usr/libexec/netdata/plugins.d/go.d.plugin`

build it and run it. It's the same file in my plugins.d folder:

```
bash-4.4# ls -l /usr/libexec/netdata/plugins.d/
total 26088
...
-rwxr-xr-x    1 root     root      26085120 Mar  1 15:00 go.d.plugin
...
bash-4.4# 
```

This is what the logs say:

```
2020-03-01 15:00:59: netdata INFO  : PLUGINSD[go.d] : connected to '/usr/libexec/netdata/plugins.d/go.d.plugin' running on pid 252
/usr/libexec/netdata/plugins.d/go.d.plugin: line 1: ����: not found
/usr/libexec/netdata/plugins.d/go.d.plugin: line 2: syntax error: unexpected word (expecting ")")
2020-03-01 15:00:59: netdata ERROR : PLUGINSD[go.d] : read failed: end of file
2020-03-01 15:00:59: netdata ERROR : PLUGINSD[go.d] : '/usr/libexec/netdata/plugins.d/go.d.plugin' (pid 252) disconnected after 0 successful data collections (ENDs). (errno 22, Invalid argument)
2020-03-01 15:00:59: netdata ERROR : PLUGINSD[go.d] : child pid 252 exited with code 2.
2020-03-01 15:00:59: netdata ERROR : PLUGINSD[go.d] : '/usr/libexec/netdata/plugins.d/go.d.plugin' (pid 252) exited with error code 2 and haven't collected any data. Disabling it. (errno 22, Invalid argument)
2020-03-01 15:00:59: netdata INFO  : PLUGINSD[go.d] : thread with task id 251 finished
```

Can you see if I am doing something wrong?

**Comment by ilyam8** [comment]
> hack/go-build.sh
Building binaries for version: v0.16.0-2-g5015bcf
Building for os/arch darwin/amd64

> Building for os/arch darwin/amd64

This, you are building it for macOS. The script builds plugin for system os/arch when there is no args provided.

https://github.com/netdata/go.d.plugin/blob/5015bcf91e96bc9978aa5158a3654c83c0f85eee/hack/go-build.sh#L71-L78

Do

> hack/go-build.sh linux

**Comment by nghtrifork** [comment]
Hi @ilyam8 
I have given it a go and I can see the extra information. However, I can also see something which perhaps can be improved:

1. Our hosts are added with the domain (e.g. host123.lan), in the metrics they are exported as `vsphere_vc.host_99_name_host123.lan_net_packets_total`. The dot in the name is still persisted, thus when I export it to graphite and check in grafana the `lan` becomes a separate grouping. I am not sure if we should just leave it as is, but what I have seen in other go.d plugins (such as mysql), some special characters (such as dash `-`) are escaped into underscore `_`

2. For both host and VM there is no "divider" between first metrics group. Example is:

How it is at the moment: 
- `vsphere_vc.vm_38_name_vm01_net_bandwith_total`
- `vsphere_vc.vm_38_name_vm01_mem_swap`

How I would expect it exports the metrics:

- `vsphere_vc.vm_38_name_vm01.net.bandwith_total`
- `vsphere_vc.vm_38_name_vm01.mem.swap`

---

Those 2 points are not directly related to the task, so I still think you can mark it as done. However, comapred to other go.d collectors I use it differs in the way it exports the metrics

**Comment by ilyam8** [comment]
> The dot in the name is still persisted

fixed in https://github.com/netdata/go.d.plugin/commit/5146e9b1c498fd876c1dfc19f866c57d3e3dceb6

___

> https://github.com/netdata/netdata/blob/master/backends/graphite/graphite.c

```c
    buffer_sprintf(
            b
            , "%s.%s.%s.%s%s%s " COLLECTED_NUMBER_FORMAT " %llu\n"
            , prefix
            , hostname
            , chart_name
            , dimension_name
            , (host->tags)?";":""
            , (host->tags)?host->tags:""
            , rd->last_collected_value
            , (unsigned long long)rd->last_collected_time.tv_sec
    );

```


i see exported metric is (the part we are interested in) `chart_name`.`dimension_name`

chart_name: `vsphere_vc.host_99_name-host123_lan`

dimension according your scheme should be `<metrics group>.<metric>`, but i cant do it that way because i need to add some uniq key to the dimension - which is vm/host id, so it becomes

`vsphere_vc.host_99_name-host123_lan.host_99_net.droppedRx.summation`

**Comment by nghtrifork** [comment]
Hi @ilyam8,

I haven't seen that commit. What I tested was the commit 5015bcf.

I am ok with the metrics setup as well as they are now. However, based on what I have seen on the other collectors I thought it differs a bit. 

Thank you for your effort

**Comment by ilyam8** [comment]
> I haven't seen that commit.

i added it 5 min ago.

> However, based on what I have seen on the other collectors I thought it differs a bit.


i dont think so, at least it is not true for go/python collectors.

Collector output is `map[string]int64`, it is map of dimensions/its values, as you see every dimenstion should have unique id, that is why there is host/vm id in the every dimension id

https://github.com/netdata/go.d.plugin/blob/5146e9b1c498fd876c1dfc19f866c57d3e3dceb6/modules/vsphere/vsphere.go#L189-L199

**Pull request merged**
