### PR TITLE
Feat(nvidia-smi): rewrite nvidia-smi module with native C API

### PR DESCRIPTION
**Pull request by Ehekatl**
not sure if it's acceptable...
this PR enables CGO, and embedded 3rd party lib directly under pkg.
I couldn't use go mod from source because I made some changes there (to fix nil point issue, etc 
Also the chart names are slightly different from python version.

Other than that everything works well, I've being use this for quite long.

### CODE REVIEW

**Comment by tycho** [comment]
Nice! This looks way better than my slow/kludgy Python garbage.

**Comment by ilyam8** [comment]
hi @Ehekatl 

> this PR enables CGO

that is what we are trying to avoid, i removed nvidia and oracledb modules because of that

https://github.com/netdata/go.d.plugin/pull/204


> I made some changes there

Why do not contribute to the upstream?

**Comment by Ehekatl** [comment]
Ya I know @ilyam8 
That's why I didn't expect to merge this. Just add it here in case someone need it, feel free to close

**Comment by ilyam8** [comment]
@Ehekatl you could write it as a standalone plugin

> https://github.com/netdata/go-orchestrator/blob/master/examples/simple/main.go

and add a link here

> https://docs.netdata.cloud/collectors/collectors/#third-party-plugins

**Pull request closed without merging**
