### PR TITLE
Nginxvts plugin

### PR DESCRIPTION
**Pull request by ski2per**
Hi,
I am trying to add NginxVts support for go.d.plugin. It supports most of NginxVts metrics currently.
Also, wish you guys can help me with this :)

### CODE REVIEW

**Comment by ilyam8** [comment]
Hi @ski2per, thx for the PR!

I suggest to use [elasticsearch](https://github.com/netdata/go.d.plugin/tree/master/modules/elasticsearch) or [couchdb](https://github.com/netdata/go.d.plugin/tree/master/modules/couchdb) modules as examples. I guess you used nginx? It was written long time ago and not a good example, i need to rewrite it.

Follow same logic - scrape stats (nginxvts needs only one endpoint) then severl collectX methods (collectServerZones, collectFilterZones, collectUpstreamZones, collectcacheZones):

https://github.com/netdata/go.d.plugin/blob/07fcd599c1bcd88340ce8f4971e9025e90a99b29/modules/elasticsearch/collect.go#L27-L40

**Comment by ski2per** [comment]
> Hi @ski2per, thx for the PR!
> 
> I suggest to use [elasticsearch](https://github.com/netdata/go.d.plugin/tree/master/modules/elasticsearch) or [couchdb](https://github.com/netdata/go.d.plugin/tree/master/modules/couchdb) modules as examples. I guess you used nginx? It was written long time ago and not a good example, i need to rewrite it.
> 
> Follow same logic - scrape stats (nginxvts needs only one endpoint) then severl collectX methods (collectServerZones, collectFilterZones, collectUpstreamZones, collectcacheZones):
> 
> https://github.com/netdata/go.d.plugin/blob/07fcd599c1bcd88340ce8f4971e9025e90a99b29/modules/elasticsearch/collect.go#L27-L40

OK, I will take a look

**Comment by ski2per** [comment]
Hi @ilyam8,
The keys for ServerZones, FilterZones and CacheZones of NginxVts are all dynamically generated, refer to  [vts-full.json](https://github.com/ski2per/go.d.plugin/blob/nginxvts-plugin/modules/nginxvts/testdata/vts-full.json).
So I generate charts dynamically. For example:
  "filterZones":{
    "b.bar.com":{
      "/login":{
        "requestCounter":1,
        "inBytes":78,
        "outBytes":314,
        "responses":{
          "1xx":0,
          "2xx":0,
          "3xx":0,
          "4xx":0,
          "5xx":1,
I merge "b.bar.com" and "/login" as new key for a chart of filterZones("b.bar.com")，and format the chart.ID like this: fmt.Sprintf(chart.ID, "b.bar.com_/login).  Then change chart.Fam and Dim's ID accordingly.
BTW, "/login" is got from Nginx variable **$uri**，this may be changed depend on NginxVts's configuration, e.g. **$request_method**.

The final output of netdata with prometheus (we use prometheus as our monitoring backend) format would be:
netdata_nginxvts_filterzones_responses_number_average{chart="nginxvts_debug.responses_b.bar.com__login",family="b.bar.com",dimension="1xx"} 0.0000000 1606735492000
netdata_nginxvts_filterzones_responses_number_average{chart="nginxvts_debug.responses_b.bar.com__login",family="b.bar.com",dimension="2xx"} 0.0000000 1606735492000
netdata_nginxvts_filterzones_responses_number_average{chart="nginxvts_debug.responses_b.bar.com__login",family="b.bar.com",dimension="3xx"} 0.0000000 1606735492000
netdata_nginxvts_filterzones_responses_number_average{chart="nginxvts_debug.responses_b.bar.com__login",family="b.bar.com",dimension="4xx"} 0.0000000 1606735492000
netdata_nginxvts_filterzones_responses_number_average{chart="nginxvts_debug.responses_b.bar.com__login",family="b.bar.com",dimension="5xx"} 1.0000000 1606735492000

Can you suggest a better way to generate dynamic charts like this? :)

**Comment by ilyam8** [comment]
@ski2per yeah,

 - chart id must be globally unique (go.d agent adds job name prefix, so the are `jobName.chartID`)
 - dimension id must be chart unique, but because of current go.d.plugin implementation - must be unique across all the jobs charts. ([we iterate over chart dimensions and try to find dimensions ids](https://github.com/netdata/go.d.plugin/blob/d3ece5befbff89e448f6cf328a648f26f8a65d99/agent/module/job.go#L403-L415) in the data returned by `Collect()`).

So we need to append stuff to the chart/dimension ids unfortunately.

---

What i suggest is to split the implementation into two steps (separate PRs)
 - collect summary statistics ({ServerZones,FilterZones,...}_total)
 - collect detailes statistics (per {ServerZones,FilterZones,...})

Does it sound good for you?

**Comment by ilyam8** [comment]
atm data export in prometheus format is not good, you have all the details in the chart/dimension id and have to parse it to extract _labels_.

There is ongoing work on adding labels to charts/dimensions (in pretty limited fashion, but still), so at some point we will be able to have charts as containers of metrics (and metric is a label set, no need to parse it) and prometheus export will export metrics, not charts.

**Comment by ski2per** [comment]
> * detailed



> @ski2per yeah,
> 
> * chart id must be globally unique (go.d agent adds job name prefix, so the are `jobName.chartID`)
> * dimension id must be chart unique, but because of current go.d.plugin implementation - must be unique across all the jobs charts. ([we iterate over chart dimensions and try to find dimensions ids](https://github.com/netdata/go.d.plugin/blob/d3ece5befbff89e448f6cf328a648f26f8a65d99/agent/module/job.go#L403-L415) in the data returned by `Collect()`).
> 
> So we need to append stuff to the chart/dimension ids unfortunately.
> 
> What i suggest is to split the implementation into two steps (separate PRs)
> 
> * collect summary statistics ({ServerZones,FilterZones,...}_total)
> * collect detailed statistics (per {ServerZones,FilterZones,...})
> 
> Does it sound good for you?

Thanks for the detailed explanation 👍 . 
I will try this.

**Comment by ski2per** [comment]
> atm data export in prometheus format is not good, you have all the details in the chart/dimension id and have to parse it to extract _labels_.
> 
> There is ongoing work on adding labels to charts/dimensions (in pretty limited fashion, but still), so at some point we will be able to have charts as containers of metrics (and metric is a label set, no need to parse it) and prometheus export will export metrics, not charts.

Good to here this.
Indeed, we are using regexp in Grafana to parse label from chart id, kind weird.

**Comment by ilyam8** [comment]
> Indeed, we are using regexp in Grafana to parse label from chart id, kind weird.

coudln't agree more 😅

**Comment by ski2per** [comment]
close this for #523

**Pull request closed without merging**
