### PR TITLE
Add TCP metrics

### PR DESCRIPTION
**Pull request by thiagoftsm**
This PR is bringing the following metrics to WMI:

### CODE REVIEW

**Comment by ilyam8** [comment]
Hi. Thanks! You added windows_service_info testdata lines in this PR (TCP). By accident, I guess. Pls, remove them.

**Comment by thiagoftsm** [comment]
> Hi. Thanks! You added windows_service_info testdata lines in this PR (TCP). By accident, I guess. Pls, remove them.

You are right, I already removed them.

**Comment by ilyam8** [comment]
@thiagoftsm, no, you didn't.

**Comment by thiagoftsm** [comment]
> @thiagoftsm, no, you didn't. I meant to say windows_service_*, not info only. I believe this should make sense for you because of the PR title (TCP).

You did not request to remvoe `windows_service_*` you asked for `windows_service_info`. :smile: 
Last commit removed the remaining metrics.

**Review by ilyam8 — APPROVED** [review]

**Comment by milindpatel63** [comment]
do we need to update the wmi collector command on our windows machine to collect these new "TCP" metrics?

Previous command was,
```
msiexec -i <path-to-msi-file> ENABLED_COLLECTORS=cpu,memory,net,logical_disk,os,system,logon,thermalzone
```
Should we just add "tcp" to enabled collectors?

**Comment by thiagoftsm** [comment]
Hello @milindpatel63 ,

You will need to add `,tcp` for the given command:

```sh
msiexec -i <path-to-msi-file> ENABLED_COLLECTORS=cpu,memory,net,logical_disk,os,system,logon,thermalzone,tcp
```

After this `windows exporter` will expose metrics and `go.d.plugin` will be able to collect.

Best regards!

**Comment by milindpatel63** [comment]
> Hello @milindpatel63 ,
> 
> You will need to add `,tcp` for the given command:
> 
> ```shell
> msiexec -i <path-to-msi-file> ENABLED_COLLECTORS=cpu,memory,net,logical_disk,os,system,logon,thermalzone,tcp
> ```
> 
> After this `windows exporter` will expose metrics and `go.d.plugin` will be able to collect.
> 
> Best regards!

Got it.
Kindly also update this info in the official docs here: https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/wmi#requirements after the changes are merged in netdata master branch.

**Comment by thiagoftsm** [comment]
Hello @milindpatel63 ,

You are right, I already push a commit updating the PR https://github.com/netdata/netdata/pull/13878, and I made a new PR on this repo (https://github.com/netdata/go.d.plugin/pull/943) to update local documentation. 

Thank you !

**Pull request merged**
