### PR TITLE
Added ReviewDog Go linting checks.

### PR DESCRIPTION
**Pull request by Ferroin**
We mistakenly added these to the agent repo instead of this one, add them here instead.

### CODE REVIEW

**Comment by ilyam8** [comment]
i think i have all those checks in circleci

**Comment by ilyam8** [comment]
anyway

**Comment by ilyam8** [comment]
was wrong
https://github.com/netdata/go.d.plugin/pull/350/checks?check_run_id=472485497

good good

**Comment by Ferroin** [comment]
As mentioned in the standup, the plan is to move to GHA as much as possible for CI. Depending on how things end up, we'll probably even ben able to do the FreeBSD builds using it.

**Pull request merged**
