### PR TITLE
Fix incorrect regexp for Cipher Suite

### PR DESCRIPTION
**Pull request by agrimal**
Fixes: #353
Closes: #355

### CODE REVIEW

**Comment by ilyam8** [comment]
@agrimal i didnt see the PR was fixing ASAP 😄 

https://github.com/netdata/go.d.plugin/pull/355

**Comment by ilyam8** [comment]
it is not enough to fix the regex, we need to add new test cases and fix `assignCipherSuite` method

**Comment by ilyam8** [comment]
@agrimal you openned PR fix, so i am ok to close mine, but please add https://github.com/netdata/go.d.plugin/pull/354#issuecomment-594103809

**Comment by agrimal** [comment]
No problem you already done all the job, just close this PR and merge yours.

**Pull request closed without merging**
