### PR TITLE
Adding new lines to fix details tag

### PR DESCRIPTION
**Pull request by hugovalente-pm**
image

### CODE REVIEW

**Comment by ilyam8** [comment]
@hugovalente-pm what is the problem? I think the syntax is ok in the metadata. Probably gen script should be adjusted not meta.

**Comment by hugovalente-pm** [comment]
while working on github issues/comments and Learn I had come across places where not having an _adequate_ split between the html element and the next piece of markdown code it was causing for the html attributes to not work properly. I thought the issue was the same here

if you think this is the gen script let's ping @Ferroin to check

**Comment by ilyam8** [comment]
Yeah, I suspect there is a problem in the gen script because there is an empty line between the end of the table and `</details>`

Screenshot 2023-09-26 at 18 07 33

**Comment by ilyam8** [comment]
@Ancairon ping

**Comment by Ancairon** [comment]
This is interesting, I would also add a newline at line 222-223

**Comment by ilyam8** [comment]
What is interesting? 🤔 I don't get why we need to add newlines in that meta file, it looks ok to me.

**Comment by Ancairon** [comment]
there is no need to, I agree, let me check what comes up in the big PR in markdown form and come back here

**Comment by Ancairon** [comment]
see https://github.com/netdata/go.d.plugin/blob/integrations-docs/modules/vcsa/integrations/vcenter_server_appliance.md

that's why I said it is interesting, this is a problem of the app not being able to properly parse markdown, that's my guess

**Comment by ilyam8** [comment]
@Ancairon asking you because we could have this problem in multiple places and we just don't know about that.

**Comment by Ancairon** [comment]
which in this case is a @kapantzak to make sure

**Comment by ilyam8** [comment]
Closing because it is not meta problem

**Pull request closed without merging**
