### PR TITLE
Set required golang to 1.21

### PR DESCRIPTION
**Pull request by k0ste**
Fixes netdata/netdata#16278

### CODE REVIEW

**Comment by ilyam8** [comment]
Thanks, @k0ste!

**Comment by k0ste** [comment]
Added another commit, Run `go get -u=patch ./...` command for major version changes. Seems this also needed for golang

**Comment by ilyam8** [comment]
@k0ste please undo the last commit, it will break the plugin in a lot of places (e.g. won't compile on FreeBSD because wgctrl - cross-compilation no longer works with latest). I have dependabot setup and I update direct dependencies, if there is something is not up to date - it breaks the plugin or requires additional actions (e.g. regenerate generated code after updating radius).

**Comment by k0ste** [comment]
Understood, done. Do I need to do something for fix the CI pipeline issue?

**Comment by ilyam8** [comment]
@k0ste rebase onto the master, mysql testes were broken in master, just pushed a commit to fix them.

**Comment by k0ste** [comment]
Rebased

**Pull request merged**
